version: "3"
services:
  server:
    build: ./server
    ports:
      - "80:80"
  client:
    build: ./client
    ports:
      - "443:443"
    depends_on: 
      - server
  redis:
    image: "redis:alpine"
