version: "3"
services:
  server:
    build: ./server
    ports:
      - "4000:4000"
  client:
    build: ./client
    ports:
      - "80:82"
    depends_on: 
      - server
  redis:
    image: "redis:alpine"
